### ISSUE TITLE
[BUG] Can't find handler for document

### ISSUE THREAD

**Issue by mrmorawski** [sunt-programator/eleventy-plugin-mathjax#83]
I followed the instructions from the repo, but when I try to build the website, I get the following error:

```
[11ty/eleventy-base-blog] Including drafts.
[11ty] Writing _site/sitemap.xml from ./content/sitemap/sitemap.xml.njk
[11ty] Writing _site/feed/feed.xml from ./content/feed/feed.njk
[11ty] Writing _site/feed/feed.json from ./content/feed/json.njk
[11ty] Writing _site/index.html from ./content/index.njk
[11ty] Writing _site/blog/index.html from ./content/blog.njk
[11ty] Writing _site/impressum/index.html from ./content/impressum.md (njk)
[11ty] Problem writing Eleventy templates: (more in DEBUG output)
[11ty] 1. Having trouble writing to "_site/404.html" from "./content/404.md" (via EleventyTemplateError)
[11ty] 2. Transform `mathjax` encountered an error when transforming ./content/404.md. (via EleventyTransformError)
[11ty] 3. Can't find handler for document (via Error)
[11ty] 
[11ty] Original error stack trace: Error: Can't find handler for document
[11ty]     at HandlerList.handlesDocument (/home/marcin/marcin.website.new/node_modules/mathjax-full/js/core/HandlerList.js:60:15)
[11ty]     at HandlerList.document (/home/marcin/marcin.website.new/node_modules/mathjax-full/js/core/HandlerList.js:64:21)
[11ty]     at Object.document (/home/marcin/marcin.website.new/node_modules/mathjax-full/js/mathjax.js:11:41)
[11ty]     at mathJaxTransform (/home/marcin/marcin.website.new/node_modules/@sunt-programator/eleventy-plugin-mathjax/eleventy.cjs:82:32)
[11ty]     at Object.<anonymous> (/home/marcin/marcin.website.new/node_modules/@sunt-programator/eleventy-plugin-mathjax/eleventy.cjs:58:5)
[11ty]     at Object.<anonymous> (/home/marcin/marcin.website.new/node_modules/@11ty/eleventy/src/BenchmarkGroup.js:32:26)
[11ty]     at Template.runTransforms (/home/marcin/marcin.website.new/node_modules/@11ty/eleventy/src/Template.js:514:30)
[11ty]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11ty]     at async Template.renderPageEntry (/home/marcin/marcin.website.new/node_modules/@11ty/eleventy/src/Template.js:799:15)
[11ty]     at async /home/marcin/marcin.website.new/node_modules/@11ty/eleventy/src/Template.js:822:21
[11ty] Copied 1 file / Wrote 0 files in 1.72 seconds (v2.0.1)
[11ty] Writing _site/blog/firstpost/index.html from ./content/blog/firstpost.md (njk)
[11ty] Writing _site/blog/fifthpost/index.html from ./content/blog/fifthpost.md (njk)
[11ty] Writing _site/blog/thirdpost/index.html from ./content/blog/thirdpost.md (njk)
[11ty] Writing _site/blog/secondpost/index.html from ./content/blog/secondpost.md (njk)
[11ty] Writing _site/blog/cbt_supplemental_guide/index.html from ./content/blog/cbt_supplemental_guide/index.md (njk)
[11ty] Writing _site/blog/fourthpost/index.html from ./content/blog/fourthpost/fourthpost.md (njk)

```

To reproduce:
I am struggling to reproduce this, it works fine on the eleventy-base-blog template that I'm editing.

Expected behaviour:
Website builds

Real behaviour:
Build fails with above error message

**Comment by mrmorawski** [comment]
Never mind, I figured it out. In my case, this means that there's something wrong with the HTML embedded in the markdown. The error message could be improved.
